# Generated by Django 4.2.26 on 2026-02-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_convert_to_utf8mb4"),
    ]

    operations = [
        migrations.AddField(
            model_name="videojob",
            name="is_favorite_only",
            field=models.BooleanField(default=False),
        ),
    ]
