# Generated by Django 4.2.29 on 2026-04-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_videojob_is_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='bg_color',
            field=models.CharField(blank=True, default='gradient', max_length=20),
        ),
        migrations.AddField(
            model_name='videojob',
            name='karaoke_color',
            field=models.CharField(blank=True, default='&H000000FF', max_length=20),
        ),
        migrations.AddField(
            model_name='videojob',
            name='text_color',
            field=models.CharField(blank=True, default='&H00FFFFFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='videojob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('awaiting_customization', 'Awaiting Customization'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=30),
        ),
    ]
