# Generated by Django 4.2.26 on 2026-04-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_videojob_bg_color_videojob_karaoke_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videojob",
            name="video_file",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
