# Generated by manual migration on 2026-05-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_videojob_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='is_learned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videojob',
            name='last_practiced',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videojob',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
