# Generated by Django 4.2.30 on 2026-05-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_videojob_is_learned_difficulty_rating_last_practiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_avatar.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
